name: Publish the released PHAR

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-22.04

    name: Release PHAR

    steps:
      - name: Extract the tag version
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF##*v}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install the dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create the PHAR file.
        run: ./pinte app:build pinte.phar --build-version=${{ steps.tag.outputs.tag }}

      - name: Upload the PHAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: pinte.phar
          path: builds/pinte.phar

      - name: Upload the PHAR to release
        run: gh release upload v${{ steps.tag.outputs.tag }} builds/pinte.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
